# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gtkit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'MBProgressHUD', '~> 1.1.0'
  # Pods for gtkit

  target 'gtkitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gtkitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
