# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaoYing' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'GTCommonKit', '~> 0.5.19'
  pod 'SDCycleScrollView', '~> 1.75'
  pod 'Masonry', '~> 1.1.0'
  pod 'MJExtension', '~> 3.0.15.1'
  pod 'UMCCommon'
  pod 'UMCSecurityPlugins'
  pod 'UMCShare/UI'
  # 集成微信(精简版0.2M)
  pod 'UMCShare/Social/ReducedWeChat'


  # Pods for TaoYing

  target 'TaoYingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TaoYingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
